cache:
  paths:
    - node_modules/

lint:
  image: node:13
  script:
    - yarn install --frozen-lockfile
    # We fetch the branches, since suggestions are limited to files changed relative to the master branch.
    - git fetch origin
    # This runs a gulp job which runs remark lint checks, both suggestions and warnings.
    - ./node_modules/.bin/gulp | tee output.log
    - bash -c '! egrep -q "(error\W)" output.log'
  only:
    - external_pull_requests
    - master

# This does a test build, which checks for broken internal links.
test-build:
  image: python:3
  script:
    - pip install -r requirements.txt mkdocs
    - mkdocs build --strict
  only:
    - external_pull_requests
    - master