# Site settings
theme: uswds-jekyll
title: TTS Handbook
description: A collection of guides and policies to help you with your work.

github_info:
  organization: 18F
  repository: handbook
  default_branch: master

exclude:
  - CONTRIBUTING.md
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go
  - vendor

styles:
  - stylesheets/screen.css

scripts:
  - assets/uswds/js/uswds.min.js
  - javascripts/jquery-3.4.1.min.js
  - javascripts/private-eye.js
  - javascripts/application.js

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "handbook_page"

collections:
  pages:
    output: true
    permalink: /:name/

url: "https://handbook.tts.gsa.gov"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
# Google Analytics & DAP tracking code for handbook
google_analytics_ua: UA-48605964-19
dap_agency: GSA

# search.gov
search_site_handle: tts-handbook

jekyll_get:
  - data: dgcommunities
    json: "https://digital.gov/communities/index.json"
