# Site settings
theme: uswds-jekyll
title: TTS Handbook
description: A collection of guides and policies to help you with your work.

github:
  organization: 18F
  repository: handbook
  default_branch: master

exclude:
- CONTRIBUTING.md
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

styles:
  - stylesheets/screen.css

scripts:
  - assets/uswds/js/uswds.min.js
  - javascripts/jquery-3.4.1.min.js
  - javascripts/private-eye.js
  - javascripts/application.js

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "handbook_page"

collections:
  pages:
    output: true
    permalink: /:name/

# Google Analytics tracking code for handbook
google_analytics_ua: UA-48605964-19

# search.gov
search_site_handle: tts-handbook

jekyll_get:
  - data: dgcommunities
    json: 'https://digital.gov/communities/index.json'

navigation:
- text: Table of Contents
  internal: true
- text: Welcome to TTS
  blurb: |
    Here's what you need to know in your first week.
  url: welcome-to-TTS/
  internal: true
  generated: true
  children:
  - children:
    - text: Welcome
      url: welcome-letter/
      internal: true
    - text: Onboarding schedule
      url: onboarding-schedule/
      internal: true
    - text: Logging in
      url: how-to-log-in
      internal: true
    - text: Equipment
      url: equipment/
      internal: true
    - text: Networks
      url: networks/
      internal: true
    - text: Benefits
      url: benefits/
      internal: true
    - text: Development and training
      url: development-and-training
      internal: true
    - text: Online Learning University (OLU)
      url: olu/
      internal: true
    - text: Travel 101
      url: travel-101/
      internal: true
    - text: GitHub 101
      url: intro-to-github/
      internal: true
- text: About TTS
  blurb: |
    <a href="https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services">Technology Transformation Services (TTS)</a> applies modern methodologies and technologies to improve the public’s experience with government by helping agencies make their services more accessible, efficient, and effective. Below is more information on both general TTS policies and the individual offices within TTS.
  url: about-us/
  internal: true
  generated: true
  children:
  - text: General information and resources
    children:
    - text: Who we are
      children:
      - text: TTS Code of Conduct
        url: code-of-conduct/
        internal: true
      - text: TTS mission, history, and values
        url: tts-history/
        internal: true
      - text: TTS org chart
        url: tts-org-chart/
        internal: true
      - text: General contacts and listservs
        url: general-contacts-and-listservs/
        internal: true
      - text: Working groups and guilds
        url: working-groups-and-guilds-101/
        internal: true
        children:
        - text: Diversity at TTS
          url: diversity/
          internal: true
        - text: Accessibility
          url: accessibility/
          internal: true
      - text: Glossary
        url: glossary/
        internal: true
      - text: Records management
        url: records-management/
        internal: true
      - text: Washington, D.C. Office
        url: washington-dc/
        internal: true

    - text: Travel and leave
      children:
      - text: Leave (HR Links)
        url: leave/
        internal: true
      - text: Travel guide (table of contents)
        url: travel-guide-table-of-contents/
        internal: true
    - text: Tech
      children:
      - text: FITARA
        url: fitara/
        internal: true
      - text: Requirements for passwords
        url: password-requirements/
        internal: true
      - text: Security incidents
        url: security-incidents/
        internal: true
      - text: Sensitive information
        url: sensitive-information/
        internal: true
    - text: Employee resources
      children:
      - text: Benefits links and resources
        url: benefits-links/
        internal: true
      - text: Conferences, events, and training
        url: conferences-events-training/
        internal: true
      - text: Emergency procedures
        url: https://docs.google.com/document/d/11tUnOegbHajqXPwSFxGtmGakupYrLgyItz4sgxAysi8/edit
        internal: false
      - text: Employee assistance program
        url: employee-assistance-program/
        internal: true
      - text: Employment verification
        url: employment-verification/
        internal: true
      - text: Hiring authorities
        url: hiring-authorities/
        internal: true
      - text: Overtime and comp time
        url: overtime-and-comp-time/
        internal: true
      - text: Performance management
        url: performance-management
        internal: true
      - text: Purchase requests
        url: purchase-requests/
        internal: true
        children:
        - text: Software under $10,000
          url: software/
          internal: true
        - text: Procurements over $10,000
          url: procurements-over-10000/
          internal: true
      - text: Resources for Deaf and Hard of Hearing individuals
        url: deaf-hoh/
        internal: true
      - text: Telework guidance
        url: telework/
        internal: true
        children:
        - text: Virtual work and moving
          url: moving/
          internal: true
      - text: Transit benefit
        url: transit-benefit/
        internal: true
    - text: Hiring, staying, or changing jobs
      children:
      - text: Hiring
        url: hiring/
        internal: true
      - text: TTSJobs
        url: ttsjobs/
        internal: true
      - text: Term extensions
        url: term-extensions/
        internal: true
      - text: Assignments and details
        url: assignee-detail/
        internal: true
      - text: Promotions
        url: promotions/
        internal: true
      - text: Leaving TTS
        url: leaving-tts/
        internal: true
  - text: Software and tools
    children:
      - text: GSA internal tools
        url: gsa-internal-tools/
        internal: true
      - text: AnyConnect (VPN client)
        url: anyconnect/
        internal: true
      - text: DocuSign (digital signatures; replaced eSign)
        url: digital-signatures/
        internal: true
      - text: Federalist (publishing platform)
        url: federalist/
        internal: true
      - text: GitHub (code repos and versioning)
        url: github/
        internal: true
      - text: Gmail
        url: gmail/
        internal: true
      - text: Google Analytics
        url: google-analytics/
        internal: true
      - text: Google Calendar
        url: google-calendar/
        internal: true
      - text: Google Drive
        url: google-drive/
        internal: true
      - text: Google Groups
        url: google-groups/
        internal: true
      - text: Google Meet (video conferencing)
        url: google-meet/
        internal: true
      - text: Meetings and meeting tools
        url: meetings-and-meeting-tools/
        internal: true
      - text: Microsoft Office for OS X
        url: office/
        internal: true
      - text: Mural.ly (collaborative whiteboard tool)
        url: murally/
        internal: true
      - text: Sharing calendars with partners
        url: sharedcalendars/
        internal: true
      - text: Sketch
        url: sketch/
        internal: true
      - text: Slack (chat client)
        url: slack/
        internal: true
      - text: Text editors
        url: text-editors/
        internal: true
      - text: Tock (time tracking)
        url: tock/
        internal: true
      - text: Trello (task and project management)
        url: trello/
        internal: true
      - text: VMware Fusion (hypervisor)
        url: vmware-fusion/
        internal: true
      - text: VMware Horizon (virtual desktop client)
        url: vmware-horizon/
        internal: true
      - text: Zoom (video conferencing)
        url: zoom/
        Internal: true
- text: TTS Offices
  blurb: |
    We’re all one family at TTS, but each office has its own norms and practices.
  url: tts-offices/
  internal: true
  generated: true
  children:
  - text: TTS Office of Operations
    children:
    - text: Business Operations
      children:
      - text: Ops
        url: ops/
        internal: true
      - text: Agreements
        url: agreements/
        internal: true
        children:
        - text: State and local agreements
          url: state-local-agreements/
          internal: true
      - text: Technology Portfolio
        url: tech-portfolio/
        internal: true
    - text: Talent team
      children:
      - text: Talent
        url: talent/
        internal: true
      - text: Federal resume guide
        url: resume
        internal: true
      - text: Refer a person
        url: https://handbook.18f.gov/talent/#referring-a-person
        internal: false
      - text: Internal TTS Opportunities
        url: https://docs.google.com/spreadsheets/d/120cF2PhzbTcCfoJ8n9L3o9brn30jOcfP5LZdZy6bElk/edit#gid=0
        internal: false
      - text: Top Secret/Sensitive Compartmented Information (TS/SCI) Clearance
        url: top-secret/
        internal: true
    - text: Outreach
      children:
      - text: Outreach
        url: outreach/
        internal: true
      - text: Social media
        url: social-media/
        internal: true
  - text: TTS Office of Acquisition
    children:
    - text: Overview of OA
      url: oa/
      internal: true
    - text: OA Operational Guidance
      url: acquisition/
      internal: true
  - text: 18F
    children:
    - text: About 18F
      children:
      - text: 18F history and values
        url: history-and-values/
        internal: true
      - text: 18F org chart
        url: https://docs.google.com/presentation/d/189TanLPSFF9MWvNr6VdfUvhBAWBSXeoCSGD2ZXRDm3s/edit#slide=id.g54b7f7db38_18_0
        internal: false
    - text: How we work
      children:
      - text: How we relate to partners
        url: how-we-relate-to-partners/
        internal: true
      - text: How we collaborate
        url: how-we-collaborate/
        internal: true
      - text: Time tracking and billing
        url: tock/#time-tracking-and-billing
        internal: false
      - text: How we staff projects
        url: staffing-projects/
        internal: true
    - text: 18F chapters
      children:
      - text: Account management
        url: account-manager/
        internal: true
        children:
        - text: Account management policy
          url: client-accounts/
          internal: true
      - text: Acquisition
        url: acqstack/
        internal: true
      - text: Design
        url: design/
        internal: true
      - text: Engineering
        url: engineering/
        internal: true
      - text: Product
        url: product/
        internal: true
      - text: Strategy
        url: strategy/
        internal: true
    - text: 18F labs
      children:
      - text: Writing Lab
        url: writing-lab/
        internal: true
      - text: Design Lab
        url: https://github.com/18F/design-lab
        internal: false
      - text: Dev Lab
        url: https://gsa-tts.slack.com/messages/CDE5DU7QC/
        internal: false
    - text: 18F locations
      children:
      - text: Distributed
        url: distributed/
        internal: true
      - text: Chicago
        url: chicago/
        internal: true
      - text: New York City
        url: new-york-city/
        internal: true
      - text: San Francisco
        url: san-francisco/
        internal: true
      - text: Washington, D.C.
        url: washington-dc/
        internal: true
    - text: 18F platforms
      children:
      - text: Cloud.gov
        url: https://cloud.gov/
        internal: false
      - text: Login.gov
        url: https://login.gov/
        internal: false
    - text: 18F team resources
      children:
      - text: Before you ship
        url: https://before-you-ship.18f.gov/infrastructure/aws/
        internal: false
      - text: Blogging
        url: blogging/
        internal: true
      - text: Doing research at 18F
        url: research-guidelines/
        internal: true
      - text: Leading projects
        url: leading-projects/
        internal: true
      - text: One-on-ones
        url: one-on-ones/
        internal: true
      - text: Open source policy
        url: https://github.com/18F/open-source-policy/blob/master/policy.md
        internal: false
      - text: Out of office expectations
        url: https://docs.google.com/document/d/1qgA-vEQ1_t5plPCAs1aCOAjK0RXQzka2hHSVhoa6v5o/edit
        internal: false
      - text: Performance Plan (FY19)
        url: 18f-performance-plan/
        internal: true
      - text: Working on an acquisition engagement
        url: working-on-an-acquisition-engagement/
        internal: true
        children:
        - text: Acquisition engagement types
          url: acquisition-engagement-types/
          internal: true
        - text: Acquisition engagement glossary
          url: working-on-an-acquisition-engagement/#acquisition-glossary
          internal: true
  - text: Office of Products and Programs (OPP)
    children:
    - text: About OPP
      children:
      - text: Overview of OPP
        url: office-of-products-and-programs/
        internal: true
      - text: OPP history
        url: opp-history/
        internal: true
      - text: OPP org chart
        url: opp-org-chart/
        internal: true
    - text: Portfolios
      children:
      - text: Data
        url: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs#DSP
        internal: false
      - text: Innovation
        url: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs#IP
        internal: false
      - text: Public Experience
        url: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs#CEP
        internal: false
      - text: Smarter IT
        url: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs#SmarterITDelivery
        internal: false
      - text: Secure Cloud
        url: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs#SecureCloud
        internal: false
      - text: 10x
        url: https://10x.gsa.gov
        internal: false
  - text: Centers of Excellence (CoE)
    children:
    - text: Overview of CoE
      url: centers-of-excellence/
      internal: true
    - text: CoE Website
      url: https://coe.gsa.gov/
      internal: false
  - text: Presidential Innovation Fellows (PIF)
    children:
    - text: PIF Website
      url: https://presidentialinnovationfellows.gov/
      internal: false
