# Site  settings
theme: uswds-jekyll
title: TTS Handbook
description: The Technology Transformation Services Handbook is an open, crowd-sourced, accessible, and living resource that aims to provide the information our team needs to do their work.

github_info:
  organization: 18F
  repository: handbook
  default_branch: main

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - node_modules
  - test
  - vendor
  - _templates

scripts:
  - assets/uswds/js/uswds.min.js
  - javascripts/jquery-3.6.0.min.js
  - javascripts/application.js

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "handbook_page"

permalink: pretty

url: "https://handbook.tts.gsa.gov"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Google Analytics & DAP tracking code for handbook
google_analytics_ua: UA-48605964-19
dap_agency: GSA
dap_subagency: TTS

# search.gov
search_site_handle: tts-handbook

# touchpoints
touchpoints_form_id: 7f027ad6

private_eye: true

jekyll_get:
  - data: dgcommunities
    json: "https://digital.gov/communities/index.json"
