title: TTS Handbook
description: >- # this means to ignore newlines
  The Technology Transformation Services Handbook is an open, crowd-sourced,
  accessible, and living resource that aims to provide the information our team
  needs to do their work.

host: https://handbook.tts.gsa.gov

# Twitter handle. Only the handle, not the URL.
twitter: gsa_tts

dap:
  agency: GSA
  subagency: TTS

ga:
  ua: UA-48605964-19

# How long of a word count before showing in page nav
inpagenavwordcount: 300

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: tts-handbook

  # This renders the results within the page instead of sending to user to search.gov.
  inline: false

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true
