name: Add a job to the Handbook
description: Add a job to the TTS Jobs page in the TTS Handbook.
title: "[TTS Jobs] Add a job: "

body:
  - type: markdown
    attributes:
      value: |
        ## Add a new job to [the Handbook](https://handbook.tts.gsa.gov/hiring-staying-or-changing-jobs/ttsjobs/).

        Please fill out the form below to request to add a new job to the TTS
        Handbook. After you submit this issue, a pull request will automatically
        be generated to make the update.
  - type: dropdown
    label: Is this job available to the public, or is it internal-only?
    validations:
      required: true
    options:
      - "public"
      - "internal-only"
  - type: input
    label: Role
    validations:
      required: true
  - type: input
    label: Link
    description: |
      For roles available to the public, this is typically a link to to the
      TTS Jobs site at https://join.tts.gsa.gov. For internal-only roles, this
      is typically a link to a Google Doc.
    validations:
      required: true
  - type: input
    label: Job opening date
    description: The date must be formatted as YYYY-MM-DD.
    validations:
      required: true
  - type: input
    label: Job closing date
    description: The date must be formatted as YYYY-MM-DD.
    validations:
      required: true
  - type: input
    label: Maximum number of applications
    description: If this job will close after receiving a certain number of
      applications, put that number here. Otherwise, leave it 0 or blank.
    validations:
      required: true
    value: 0
  - type: dropdown
    label: Does this job close when all selections have been made?
    validations:
      required: true
    value: "no"
    options:
      - "no"
      - "yes"
  - type: markdown
    attributes:
      value: |
        **PLEASE NOTE:** If you need to edit this job before it is published,
        you must close this issue and create a new one. If you need to edit this
        job *after* it is published, you will have to edit the jobs data file
        directly.
