backend:
  name: github
  repo: 18f/handbook
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  open_authoring: true

media_folder: images/
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
    - name: "_pages"
      label: "Pages"
      label_singular: "page"
      nested: { depth: 3 }
      folder: "_pages/"
      create: true
      meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "launching-software"
      label: "Launching software"
      label_singular: "Launching software page"
      folder: "launching-software/"
      create: true
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "performance-management"
      label: "Performance management"
      label_singular: "Performance management page"
      folder: "performance-management/"
      create: true
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "tools"
      label: "Tools"
      label_singular: "Tools page"
      folder: "tools/"
      create: true
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
