backend:
  name: github
  repo: 18f/handbook
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  open_authoring: true

media_folder: images/
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
    - name: "pages"
      label: "Pages"
      label_singular: "Page"
      description: "Basic Handbook page"
      folder: "_pages/netlifycms"
      create: true
      slug: "{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
