backend:
  name: github
  repo: 18f/handbook
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: images/
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
    - name: "_pages"
      label: "Pages"
      label_singular: "page"
      nested: { depth: 4 }
      folder: "_pages/"
      create: true
      meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Questions", name: "questions", widget: "list"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "other"
      label: "Other"
      files:
        - label: "Contributing"
          name: "contributing"
          file: "CONTRIBUTING.md"
          fields: 
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Questions", name: "questions", widget: "list"}
            - {label: "Body", name: "body", widget: "markdown"}
 
