name: pre-commit

on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          path: docs
          ignore_words_file: .codespell-ignore
