name: pull request

on: [pull_request]

jobs:
  format:
    name: format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Use the branch commit instead of the PR merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: format markdown
        run: npx prettier .

      - name: commit changes, if necessary
        id: commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: format files

      - name: leave a comment, if necessary
        uses: actions/github-script@0.3.0
        if: steps.commit.outputs.committed == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `I have formatted the code. Please @${context.actor} pull the last commit before pushing any more changes.`
            });
