name: regular integrity check

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: cache_key
        run: echo "cache_key=${{ hashFiles('**/**') }}-v1" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v3
        id: cache
        with:
          path: .
          key: ${{ steps.cache_key.outputs.cache_key }}

      - if: steps.cache.outputs.cache-hit != true
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - if: steps.cache.outputs.cache-hit != true
        run: npm install

      - if: steps.cache.outputs.cache-hit != true
        env:
          ELEVENTY_ENV: production
        run: npm run build

      - name: check integrity
        uses: actions/github-script@v6
        with:
          script: require("./integrity-check.js");
