name: add new TTS job

on:
  issues:
    types: [opened]
  push:

jobs:
  add_job:
    name: add a new TTS job
    runs-on: ubuntu-latest

    steps:
      - run: pwd
      - run: ls
      - name: bob's burgers
        uses: actions/github-script@v6
        with:
          script: |
            console.log(__dirname)
            const script = require("./workflows/new-job-issue.js");
            await script({ context, github });