name: add new TTS job

on:
  issues:
    types: [opened]
  push:

jobs:
  add_job:
    name: add a new TTS job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: bob's burgers
        uses: actions/github-script@v6
        with:
          script: |
            const script = require("./.github/workflows/new-job-issue.js");
            await script({ context, github });