name: add new TTS job

on:
  issues:
    types: [opened]
  push:

jobs:
  add_job:
    name: add a new TTS job
    runs-on: ubuntu-latest

    steps:
      - name: bob's burgers
        uses: actions/github-script@v6
        with:
          script: |
            if(true || context.issue.number) {
              const { data: { body } } = await github.rest.issues.get({ ...context.issue, issue_number: 3380 });
              console.log(body);
            }
